Capstone.Web/Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Capstone.Web.DAL;
using Capstone.Web.Models;
using System.Configuration;
using Capstone.Web.Models.Data;


namespace Capstone.Web.Controllers
{
    public class StaffController : HomeController
    {
        private User loggedInUser = new User();

        public ActionResult StaffHome(string userName)
        {
            IUserDal idal = new UserSqlDal();
            loggedInUser = idal.GetUser(userName);
            ViewBag.UserRole = loggedInUser.User_Role;
            ViewBag.username = loggedInUser.Username;
            return View("StaffHome");
        }

        // GET: Staff
        public ActionResult ViewEmployerSchedule()
        {
            //need to remove hard coding
            int matchmakingId = 1;

            CreateArrangementDropDownList();

            EmployerDAL edal = new EmployerDAL();

            List<Employer> employers = edal.GetAllEmployers(matchmakingId);

            List<SelectListItem> employerNames = new List<SelectListItem>();

            foreach (Employer e in employers)
            {
                employerNames.Add(new SelectListItem { Text = e.EmployerName, Value = e.EmployerId.ToString() });
            }

            ViewBag.EmployerNames = employerNames;

            InterviewDAL iDAL = new InterviewDAL();

            List<Interview> masterSchedule = iDAL.GetMasterSchedule(matchmakingId);

            return View(masterSchedule);

        }

        public ActionResult AssignRoom()
        {
            //remove hardcoding
            int matchmakingId = 1;

            CreateArrangementDropDownList();

            EmployerDAL eDAL = new EmployerDAL();
            List<EmployerTeam> employerList = eDAL.GetAllEmployersAndTeams(matchmakingId);

            return View(employerList);
        }

        public ActionResult UpdateRoom()
        {
            System.Collections.Specialized.NameValueCollection parameters = Url.RequestContext.HttpContext.Request.Params;

            //remove hardcoding
            int matchmakingId = 1;

            EmployerDAL eDAL = new EmployerDAL();
            List<EmployerTeam> employerList = eDAL.GetAllEmployersAndTeams(matchmakingId);

            foreach (EmployerTeam e in employerList)
            {

                e.AssignedRoom = (!String.IsNullOrEmpty(Request.Params[e.EmployerName + e.TeamId + "assignedRoom"])) ? Request.Params[e.EmployerName + e.TeamId + "assignedRoom"] : "";

            }

            bool isSuccessful = eDAL.UpdateAssignedRoom(employerList);

            ViewBag.Message = (isSuccessful) ? "The rooms was successfully added." : "The room was not successfully added. Please try again.";

            IUserDal idal = new UserSqlDal();
            loggedInUser = idal.GetUser((Request.Params["userName"]));
            ViewBag.UserRole = loggedInUser.User_Role;

            return View("StaffHome");
        }

        public ActionResult ViewMasterSchedule()
        {
            //need to remove hardcoding
            int matchmakingId = 1;

            CreateArrangementDropDownList();

            InterviewDAL iDAL = new InterviewDAL();
            List<Interview> masterSchedule = iDAL.GetMasterSchedule(matchmakingId);

            return View(masterSchedule);
        }

        public ActionResult ViewAStudentsSchedule()
        {
            //need to remove hardcoding
            int matchmaking = 1;

            CreateArrangementDropDownList();

            StudentDAL sdal = new StudentDAL();

            List<Student> students = sdal.GetAllStudents();

            List<SelectListItem> studentNames = new List<SelectListItem>();

            foreach (Student s in students)
            {
                studentNames.Add(new SelectListItem { Text = s.StudentName, Value = s.StudentId.ToString() });
            }

            ViewBag.StudentNames = studentNames;

            InterviewDAL idal = new InterviewDAL();

            List<Interview> studentSchedules = idal.GetAllStudentsSchedules(matchmaking);

            return View(studentSchedules);
        }

        public ActionResult AddAStudentLogin()
        {
            CreateArrangementDropDownList();

            return View();
        }

        public ActionResult AddStaffLogin()
        {
            return View("AddStaffLogin");
        }

        public ActionResult UpdateStudentLogin()
        {
            System.Collections.Specialized.NameValueCollection parameters = Url.RequestContext.HttpContext.Request.Params;

            //need to add capability to email the student the username and password

            Student s = new Student();

            if ((!String.IsNullOrEmpty(Request.Params["studentName"])) && (!String.IsNullOrEmpty(Request.Params["userName"]))
                    && (!String.IsNullOrEmpty(Request.Params["languageId"])) && (!String.IsNullOrEmpty(Request.Params["matchmakingId"])))
            {
                s.StudentName = Request.Params["studentName"];
                s.UserName = Request.Params["userName"];
                s.LanguageId = int.Parse(Request.Params["languageId"]);
                s.MatchmakingId = int.Parse(Request.Params["matchmakingId"]);
            }

            StudentDAL sdal = new StudentDAL();

            bool isSuccessful = sdal.AddNewStudent(s);

            ViewBag.Message = (isSuccessful) ? "The student was successfully added." : "The student was not successfully added. Please try again.";


            // HERE Email Send
            IUserDal idal = new UserSqlDal();
            loggedInUser = idal.GetUser((Request.Params["userName"]));
            ViewBag.UserRole = loggedInUser.User_Role;

            return View("StaffHome");

        }

        public ActionResult UpdateStaffLogin()
        {
            System.Collections.Specialized.NameValueCollection parameters = Url.RequestContext.HttpContext.Request.Params;

            //need to add capability to email the staff the username and password

            User u = new User();

            if ((!String.IsNullOrEmpty(Request.Params["staffName"])) && (!String.IsNullOrEmpty(Request.Params["userName"])))
            {
                u.Username = Request.Params["userName"];
                u.StaffName = Request.Params["staffName"];
            }

            u.User_Role = ((Request.Params["isAdmin"]) == "Yes") ? "admin" : "staff";

            UserSqlDal udal = new UserSqlDal();

            bool isSuccessful = udal.AddNewStaff(u);

            ViewBag.Message = (isSuccessful) ? "The staff was successfully added." : "The staff was not successfully added. Please try again.";

            // HERE Email Send
            IUserDal idal = new UserSqlDal();
            loggedInUser = idal.GetUser((Request.Params["userName"]));
            ViewBag.UserRole = loggedInUser.User_Role;
            return View("StaffHome");

        }

        public ActionResult AddEmployer()
        {
            return View();
        }

        public ActionResult UpdateEmployer()
        {
            System.Collections.Specialized.NameValueCollection parameters = Url.RequestContext.HttpContext.Request.Params;

            Employer e = new Employer();

            if ((!String.IsNullOrEmpty(Request.Params["employerName"])) && (!String.IsNullOrEmpty(Request.Params["employerSummary"])))
            {
                e.EmployerName = Request.Params["employerName"];
                e.Summary = Request.Params["employerSummary"];
                e.NumberOfTeams = 1; //initially set this value to 1. Staff have the option to update it when they create an event
            }

            EmployerDAL edal = new EmployerDAL();

            bool isSuccessful = edal.AddNewEmployer(e);

            ViewBag.Message = (isSuccessful) ? "The employer was successfully added." : "The employer was not successfully added. Please try again.";

            IUserDal idal = new UserSqlDal();
            loggedInUser = idal.GetUser((Request.Params["userName"]));
            ViewBag.UserRole = loggedInUser.User_Role;

            return View("StaffHome");
        }

        public ActionResult CreateNewArrangement()
        {
            MatchmakingArrangement arrangement = new MatchmakingArrangement();
            return View(arrangement);
        }

        public ActionResult UpdateArrangement()
        {
            System.Collections.Specialized.NameValueCollection parameters = Url.RequestContext.HttpContext.Request.Params;

            MatchmakingArrangement arrangement = new MatchmakingArrangement();

            if ((!String.IsNullOrEmpty(Request.Params["season"])) && (!String.IsNullOrEmpty(Request.Params["location"]))
                    && (!String.IsNullOrEmpty(Request.Params["numberOfStudentChoices"])) && (!String.IsNullOrEmpty(Request.Params["cohortNumber"])))
            {
                arrangement.Location = Request.Params["location"];
                arrangement.Season = Request.Params["season"];
                arrangement.CohortNumber = int.Parse(Request.Params["cohortNumber"]);
                arrangement.NumberOfStudentChoices = int.Parse(Request.Params["numberOfStudentChoices"]);
            }

            EventDAL edal = new EventDAL();

            bool isSuccessful = edal.AddNewArrangement(arrangement);

            ViewBag.Message = (isSuccessful) ? "The arrangement was successfully added." : "The arrangement was not successfully added. Please try again.";

            IUserDal idal = new UserSqlDal();
            loggedInUser = idal.GetUser((Request.Params["userName"]));
            ViewBag.UserRole = loggedInUser.User_Role;

            return View("StaffHome");

        }

        public ActionResult AddNewEvent()
        {
            CreateArrangementDropDownList();

            ViewBag.Hours = hours;
            ViewBag.Minutes = minutes;
            ViewBag.AMPM = ampm;

            return View();
        }

        public ActionResult UpdateEvent()

Capstone.Web/Views/Staff/AddEmployer.cshtml
@{
    ViewBag.Title = "AddEmployer";
}

<h2>Add Employer</h2>

<form action="UpdateEmployer" method="post">

    @{string loggedInUserName = ViewBag.userName; }
    @Html.Hidden("userName", loggedInUserName)

    <div>
        <div class="col-sm-5 col-sm-offset-1">
            <div class="form-group label-floating">
                <label class="control-label">Employer Name </label>
                <input type="text" name="employerName" class="form-control" id="">
            </div>
        </div>
        <div class="col-sm-5 col-sm-offset-1">
            <div class="form-group label-floating">
                <label class="control-label">Employer Summary</label>
                <input type="text" name="employerSummary" class="form-control" id="">
            </div>
        </div>
    </div>
    <div class="col-sm-10">
        <div class="pull-left">
            <input value="Update" type="submit" class='btn btn-fill btn-success btn-wd btn' id="inputButton" />
        </div>
    </div>

</form>

Capstone.Web/Views/Staff/AddNewEvent.cshtml
@{
    ViewBag.Title = "AddNewEvent";
}

<h2>Add New Event</h2>

<form action="UpdateEvent" method="post">
    @{string loggedInUserName = ViewBag.userName; }
    @Html.Hidden("userName", loggedInUserName);

    @*@using (Html.BeginForm("UpdateEvent", "Staff"))
        {*@
    <div>
        @Html.Label("Pick a co-hort's a matchmaking event:")
        @Html.DropDownList("matchmakingId", (List<SelectListItem>)ViewBag.Arrangements)
    </div>


    <div>
        @Html.Label("How long is each interview?  Please include the 5 minute break:")
        @Html.DropDownList("interviewLength", (List<SelectListItem>)ViewBag.Minutes) minutes.
    </div>

    <div>
        @Html.Label("Date of the Event:")
        @Html.TextBox("date", "", new { type = "date" })
    </div>


    <div>
        @Html.Label("Start Time:")
        @Html.DropDownList("startHour", (List<SelectListItem>)ViewBag.Hours)
        @Html.DropDownList("startMinute", (List<SelectListItem>)ViewBag.Minutes)
        @Html.DropDownList("startAMPM", (List<SelectListItem>)ViewBag.AMPM)
        @Html.Label("End Time:")
        @Html.DropDownList("endHour", (List<SelectListItem>)ViewBag.Hours)
        @Html.DropDownList("endMinute", (List<SelectListItem>)ViewBag.Minutes)
        @Html.DropDownList("endAMPM", (List<SelectListItem>)ViewBag.AMPM)
    </div>
    <h5>Select N/A if there are no lunch or break periods.</h5>
    <div>
        @Html.Label("Lunch Start:")
        @Html.DropDownList("lunchStartHour", (List<SelectListItem>)ViewBag.Hours)
        @Html.DropDownList("lunchStartMinute", (List<SelectListItem>)ViewBag.Minutes)
        @Html.DropDownList("lunchStartAMPM", (List<SelectListItem>)ViewBag.AMPM)
        @Html.Label("Lunch End:")
        @Html.DropDownList("lunchEndHour", (List<SelectListItem>)ViewBag.Hours)
        @Html.DropDownList("lunchEndMinute", (List<SelectListItem>)ViewBag.Minutes)
        @Html.DropDownList("lunchEndAMPM", (List<SelectListItem>)ViewBag.AMPM)
    </div>

    <div>
        @Html.Label("Morning Break Start:")
        @Html.DropDownList("MBStartHour", (List<SelectListItem>)ViewBag.Hours)
        @Html.DropDownList("MBStartMinute", (List<SelectListItem>)ViewBag.Minutes)
        @Html.DropDownList("MBStartAMPM", (List<SelectListItem>)ViewBag.AMPM)
        @Html.Label("Morning Break End:")
        @Html.DropDownList("MBEndHour", (List<SelectListItem>)ViewBag.Hours)
        @Html.DropDownList("MBEndMinute", (List<SelectListItem>)ViewBag.Minutes)
        @Html.DropDownList("MBEndAMPM", (List<SelectListItem>)ViewBag.AMPM)
    </div>

    <div>
        @Html.Label("Afternoon Break Start:")
        @Html.DropDownList("ABStartHour", (List<SelectListItem>)ViewBag.Hours)
        @Html.DropDownList("ABStartMinute", (List<SelectListItem>)ViewBag.Minutes)
        @Html.DropDownList("ABStartAMPM", (List<SelectListItem>)ViewBag.AMPM)


        @Html.Label("Afternoon Break End:")
        @Html.DropDownList("ABEndHour", (List<SelectListItem>)ViewBag.Hours)
        @Html.DropDownList("ABEndMinute", (List<SelectListItem>)ViewBag.Minutes)
        @Html.DropDownList("ABEndAMPM", (List<SelectListItem>)ViewBag.AMPM)
    </div>

    <div class="col-sm-10">
        <div class="pull-left">
            @* <input value="Submit" type="submit" id="inputButton" />*@

            <input value="Submit" type="submit" class='btn btn-fill btn-success btn-wd btn' id="inputButton" />

            @* <input type='button'  id="inputButton" class='btn btn-fill btn-primary btn-wd btn-sm' name='Submit' value='Submit' />*@
        </div>
    </div>
    @*}*@

</form>

Capstone.Web/Views/Staff/AddStaffLogin.cshtml
@{
    ViewBag.Title = "AddAStudentLogin";
}

<h2>Create A Staff Login</h2>


<form action="UpdateStaffLogin" method="post">
    @{string loggedInUserName = ViewBag.userName; }
    @Html.Hidden("userName", loggedInUserName);

    @*@using (Html.BeginForm("UpdateStaffLogin", "Staff"))
        {*@
    <table>
        <tr>
            <td>@Html.Label("Staff Name: ")</td>
            <td>@Html.TextBox("staffName")</td>
        </tr>
        <tr>
            <td>@Html.Label("Staff's User Name: ")</td>
            <td>@Html.TextBox("userName")</td>
        </tr>
        <tr>
            <td>@Html.Label("Staff's email address: ")</td>
            <td>@Html.TextBox("emailAddress")</td>
        </tr>
        <tr>
            <td>@Html.Label("Confirm staff's email address: ")</td>
            <td>@Html.TextBox("emailAddress2")</td>
        </tr>
        <tr>
            <td>@Html.Label("Is the staff a admin: ")</td>
            <td>
                @Html.DropDownList("isAdmin", new SelectList(new List<Object>{new { value = "Yes" , text = "Yes" },
                    new { value = "No" , text = "No"}}, "value", "text", 2))
            </td>
        </tr>
        <tr>
            <td>Initial Passwords are set to "Password"</td>
        </tr>
    </table>

    <div class="col-sm-10">
        <div class="pull-left">
            @* <input value="Submit" type="submit" id="inputButton" />*@

            <input value="Submit" type="submit" class='btn btn-fill btn-success btn-wd btn' id="inputButton" />

            @* <input type='button'  id="inputButton" class='btn btn-fill btn-primary btn-wd btn-sm' name='Submit' value='Submit' />*@
        </div>
    </div>
    @*}*@
</form>

Capstone.Web/Views/Staff/AssignRoom.cshtml
@using Capstone.Web.Models;

@model List<EmployerTeam>

@{
    ViewBag.Title = "AssignRoom";
}


<h2>Update Rooms</h2>


<div>@Html.Label("Please pick a matchmaking event:")</div>
<div>@Html.DropDownList("matchmakingId", (List<SelectListItem>)ViewBag.Arrangements)</div>

@*@using (Html.BeginForm("UpdateRoom", "Staff"))
{*@

<form action="UpdateRoom" method="post">
    @{string loggedInUserName = ViewBag.userName; }
    @*@ViewBag.userName;
    @ViewBag.UserRole;*@
    <input id="userName" name="userName" type="hidden" value="@ViewBag.userName" />;

    @Html.Hidden("userName", loggedInUserName);
    <table>
        <tr>
            <td>@Html.Label("Employer Name")</td>
            <td>@Html.Label("Team Number")</td>
            <td>@Html.Label("Assign Room")</td>
        </tr>
        @foreach (EmployerTeam e in Model)
        {
            <tr>
                <td>@Html.Label(e.EmployerName)</td>
                <td>@Html.Label(e.TeamId.ToString())</td>
                <td>@Html.TextBox(e.EmployerName + e.TeamId + "assignedRoom", e.AssignedRoom)</td>
            </tr>
        }

    </table>

    <div class="col-sm-10">
        <div class="pull-left">
            @* <input value="Submit" type="submit" id="inputButton" />*@

            <input value="Submit" type="submit" class='btn btn-fill btn-success btn-wd btn' id="inputButton" />

            @* <input type='button'  id="inputButton" class='btn btn-fill btn-primary btn-wd btn-sm' name='Submit' value='Submit' />*@
        </div>
    </div>
    @*}*@
    </form>

Capstone.Web/Views/Staff/CreateNewArrangement.cshtml
@{
    ViewBag.Title = "Create Cohort's Matchmaking Arrangement";
}

<h2>Create A New Arrangement</h2>


<form action="UpdateArrangement" method="post">

    @*@using (Html.BeginForm("UpdateArrangement", "Staff"))
    {*@
    @{string loggedInUserName = ViewBag.userName; }
    @Html.Hidden("userName", loggedInUserName);
        <table>
            <tr>
                <td>@Html.Label("Which Location are you scheduling for? ")</td>
                <td>
                    @Html.DropDownList("location", new SelectList(new List<Object>{new { value = "Columbus" , text = "Columbus" },
                    new { value = "Cleveland" , text = "Cleveland"}}, "value", "text", 2))
            </td>
        </tr>
        <tr>
            <td>@Html.Label("What is the Cohort Number: ")</td>
            <td>@Html.TextBox("cohortNumber")</td>
        </tr>
        <tr>
            <td>@Html.Label("Which season are you scheduling for? ")</td>
            <td>
                @Html.DropDownList("season", new SelectList(new List<Object>{new { value = "Fall" , text = "Fall" }, new { value = "Winter" , text = "Winter" },
                    new { value = "Spring" , text = "Spring"}, new { value = "Summer" , text = "Summer" },}, "value", "text", 2))
            </td>
        </tr>
        <tr>
            <td>@Html.Label("How many employer choices will the students get : ")</td>
            <td>@Html.TextBox("numberOfStudentChoices")</td>
        </tr>

    </table>

    <div class="col-sm-10">
        <div class="pull-left">
            @* <input value="Submit" type="submit" id="inputButton" />*@

            <input value="Submit" type="submit" class='btn btn-fill btn-success btn-wd btn' id="inputButton" />

            @* <input type='button'  id="inputButton" class='btn btn-fill btn-primary btn-wd btn-sm' name='Submit' value='Submit' />*@
        </div>
    </div>
    @*}*@
    </form>

Capstone.Web/Views/Staff/GenerateSchedule.cshtml
@{
    ViewBag.Title = "Generate Schedule";
}

<h2>@ViewBag.Title</h2>

<form action="" method="post">
    <div>
        @Html.Label("Pick a co-hort's a matchmaking event:")
        @Html.DropDownList("matchmakingId", (List<SelectListItem>)ViewBag.Arrangements)
    </div>
    <h2>This will generate the master schedule.  Please verify that there will be no more changes to this Cohort's Matchmaking Arrangements</h2>
    <div class="col-sm-10">
        <div class="pull-left">
            <input value="Submit" type="submit" class='btn btn-fill btn-success btn-wd btn' id="inputButton" />
        </div>
    </div>
</form>

Capstone.Web/Views/Staff/PickArrangement.cshtml
@{
    ViewBag.Title = "Pick the Cohort's Matchmaking Arrangement";
}

<h2>@ViewBag.Title</h2>

<form action="AssignParticipantsToEvent" method="post">
    @{string loggedInUserName = ViewBag.userName; }
    @Html.Hidden("userName", loggedInUserName)

    @*@using (Html.BeginForm("AssignParticipantsToEvent", "Staff"))
    {*@
    <div>
        @Html.Label("Pick a co-hort's a matchmaking event:")
        @Html.DropDownList("matchmakingId", (List<SelectListItem>)ViewBag.Arrangements)
    </div>
    <div class="col-sm-10">
        <div class="pull-left">
            @* <input value="Submit" type="submit" id="inputButton" />*@

            <input value="Submit" type="submit" class='btn btn-fill btn-success btn-wd btn' id="inputButton" />

            @* <input type='button'  id="inputButton" class='btn btn-fill btn-primary btn-wd btn-sm' name='Submit' value='Submit' />*@
        </div>
    </div>
</form>

Capstone.Web/Views/Staff/Staff.cshtml
@{

}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>
    <div> 
    </div>
</body>
</html>

Capstone.Web/Views/Staff/StaffHome.cshtml
@model Capstone.Web.Models.Users.LoginViewModel
@{
    ViewBag.Title = "Staff Home";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<script type="text/javascript" src="~/Scripts/js/Login.js"></script>
<link type="text/css" rel="stylesheet" href="~/Content/css/crus.css" />

<div class="image-container set-full-height">
    <link type="text/css" rel="stylesheet" href="~/Content/css/crus.css" />



    <a href="~/About/About" style="" target="_blank">
        <div class="logo-container_01">
            <div class="logo">
                <img src="http://demos.creative-tim.com/material-bootstrap-wizard/assets/img/new_logo.png">
            </div>
                @ViewBag.userName
        </div>
    </a>
    <a href="#" style="" target="_blank">
        <div class="logo-container_02">

            <div class="brand">
                Log out
            </div>
        </div>
    </a>
    <a href="~/About/About" class="made-with-mk" target="_blank">
        <div class="brand">ET</div>
        <div class="made-with">Made by <strong>Echo Team</strong></div>
    </a>

    <!--   Big container   -->
    <div class="container">
        <div class="row" style="width: 1500px">
            <div class="col-sm-12">
                <!-- Wizard container -->
                <div class="wizard-container">
                    <div class="card wizard-card" data-color="green" id="wizard">
                        <div class="wizard-header">
                            <h3 class="wizard-title">
                                Staff Home
                            </h3>
                        </div>
                        <div class="wizard-navigation" style="width: 1450px">
                            <ul>
                                <li><a href="#description_08" data-toggle="tab">Add Staff</a></li>
                                <li><a href="#details" data-toggle="tab">Add Student</a></li>
                                <li><a href="#captain" data-toggle="tab">Add Employer</a></li>
                                @*<li><a href="#description_01" data-toggle="tab">Update Status</a></li>*@
                                @*<li><a href="#description_02" data-toggle="tab">View Student Schedule</a></li>*@                                                                
                                <li><a href="#description_05" data-toggle="tab">Create Arrangment</a></li>
                                <li><a href="#description_06" data-toggle="tab">Add Event</a></li>
                                <li><a href="#description_07" data-toggle="tab">Update Event</a></li>
                                <li><a href="#description_03" data-toggle="tab">Generate Schedule</a></li>  
                                <li><a href="#description_04" data-toggle="tab">View Master Schedule</a></li>
                                <li><a href="#description" data-toggle="tab">Assign Room</a></li> 
                            </ul>
                        </div>

                        <div class="tab-content">
                            <div class="tab-pane" id="description_02">
                                <div class="row">
                                    @Html.Action("ViewAStudentsSchedule", "Staff")

                                </div>
                            </div>
                            <div class="tab-pane" id="details">
                                <div class="row">
                                    <div class="col-sm-12">
                                        @Html.Action("AddAStudentLogin", "Staff")
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane" id="captain">
                                <div class="row" style="width: 1200px">
                                    <div class="col-sm-12 ">
                                        @Html.Action("AddEmployer", "Staff")
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane" id="description">
                                <div class="row">
                                    @Html.Action("AssignRoom", "Staff")
                                    <div class="col-sm-6 col-sm-offset-1">
                                        <div class="form-group">
                                            @*<label>Room description</label>*@
                                            <textarea class="form-control" placeholder="" rows="6"></textarea>
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="form-group">
                                            @*<label class="control-label">Example</label>*@
                                            @*<p class="description">"The room really nice name is recognized as being a really awesome room. We use it every sunday when we go fishing and we catch a lot. It has some kind of magic shield around it."</p>*@
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane" id="description_01">
                                <div class="row">
                                    @*  @Html.Action("UpdateStatus", "Staff") *@
                                    @*<h4 class="info-text"> Drop us a small description.</h4>*@
                                    <div class="col-sm-6 col-sm-offset-1">
                                        <div class="form-group">
                                            <label>@*Room description*@</label>
                                            <textarea class="form-control" placeholder="" rows="6"></textarea>
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="form-group">
                                            @*<label class="control-label">Example</label>*@
                                            @*     <p class="description">"The room really nice name is recognized as being a really awesome room. We use it every sunday when we go fishing and we catch a lot. It has some kind of magic shield around it."</p>*@
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane" id="description_03">
                                <div class="row">
                                    @Html.Action("GenerateSchedule", "Staff")
                                    @* <h4 class="info-text"> Drop us a small description.</h4>*@
                                    <div class="col-sm-6 col-sm-offset-1">
                                        <div class="form-group">
                                            @*<h4 class="info-text"> Drop us a small description.</h4>*@
                                            @*<label>Room description</label>*@
                                            <textarea class="form-control" placeholder="" rows="6"></textarea>
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="form-group">
                                            @*<label class="control-label">Example</label>*@
                                            @*<p class="description">"The room really nice name is recognized as being a really awesome room. We use it every sunday when we go fishing and we catch a lot. It has some kind of magic shield around it."</p>*@
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane" id="description_04">
                                <div class="row">
                                    @Html.Action("ViewMasterSchedule", "Staff")
                                    @*<h4 class="info-text"> Drop us a small description.</h4>*@
                                </div>
                            </div>
                            <div class="tab-pane" id="description_08">
                                <div class="row">
                                    @Html.Action("AddStaffLogin", "Staff")

                                </div>
                            </div>
                            <div class="tab-pane" id="description_05">
                                <div class="row">
                                    @Html.Action("CreateNewArrangement", "Staff")

                                </div>
                            </div>
                            <div class="tab-pane" id="description_06">
                                <div class="row">
                                    @Html.Action("AddNewEvent", "Staff")

                                </div>
                            </div>
                            <div class="tab-pane" id="description_07">
                                <div class="row">
                                    @Html.Action("PickArrangement", "Staff")

                                </div>
                            </div>
                            <div class="tab-pane" id="description_10">
                                <div class="row">
                                    @Html.Action("AssignParticipantsToEvent", "Staff")

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer">
    </div>
</div>